using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using L2Flag;

namespace LM2RandomiserMod
{
    public abstract class ItemFlags
    {
        public static L2FlagBoxEnd[] GetItemGetFlags(ItemID id)
        {
            L2FlagBoxEnd[] result = null;
            getFlags.TryGetValue(id, out result);
            return result;
        }
        
        public static ItemInfo GetItemInfo(ItemID id)
        {
            ItemInfo result = null;
            itemData.TryGetValue(id, out result);
            return result;
        }
        
        //kinda needed for items that have extra flags
        private static readonly Dictionary<ItemID, L2FlagBoxEnd[]> getFlags = new Dictionary<ItemID, L2FlagBoxEnd[]>
        {
            {ItemID.HandScanner,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 0, data = 1 }}},
            {ItemID.DjedPillar,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 1, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Mjolnir,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 2, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Beherit,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 3, data = 1 }}},
            {ItemID.AncientBattery,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 4, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.LampofTime,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 5, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.PochetteKey,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 6, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.PyramidCrystal,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 7, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 8, data = 1 }}},
            {ItemID.Vessel,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 9, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Pepper,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 10, data = 1 }}},
            {ItemID.EggofCreation,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 11, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.GiantsFlute,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 12, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CogofAntiquity,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 13, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.MulanaTalisman,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 14, data = 1 }}},

            {ItemID.MobileSuperx3P,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 15, data = 2 }}},
            {ItemID.ShellHorn,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 16, data = 1 }}},
            {ItemID.HolyGrail,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 17, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.FairyPass,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 18, data = 1 }}},
            {ItemID.Gloves,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 19, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.DinosaurFigure,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 20, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.GaleFibula,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 21, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.FlameTorc,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 22, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Vajra,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 23, data = 1 }}},
            {ItemID.PowerBand,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 24, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.BronzeMirror,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 25, data = 1 }}},
            {ItemID.Perfume,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 26, data = 1 }}},
            {ItemID.IceCloak,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 27, data = 1 }}},
            {ItemID.NemeanFur,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 28, data = 1 }}},
            {ItemID.Gauntlet,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 29, data = 1 }}},
            {ItemID.Anchor,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 30, data = 1 }}},
            {ItemID.FreyasPendant,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 31, data = 1 }}},
            {ItemID.TotemPole,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 32, data = 1 }}},
            {ItemID.GrappleClaw,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 33, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Spaulder,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 34, data = 1 }}},
            {ItemID.Scalesphere,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 35, data = 1 }}},
            {ItemID.Crucifix,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 36, data = 1 }}},
            {ItemID.GaneshaTalisman,            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 37, data = 1 },   //Ganesha's Talisman
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.MaatsFeather,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 38, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Ring,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 39, data = 1 }}},
            {ItemID.Bracelet,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 40, data = 1 }}},
            {ItemID.Feather,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 41, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Scriptures,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 42, data = 1 }}},
            {ItemID.FreysShip,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 43, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.Codices,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 44, data = 1 }}},
            {ItemID.SnowShoes,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 45, data = 1 }}},
            {ItemID.Harp,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 46, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.BookoftheDead,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 47, data = 1 }}},
            {ItemID.LightScythe,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 48, data = 1 }}},
            {ItemID.DestinyTablet,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 49, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.SecretTreasureofLife,       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 50, data = 1 }}},

            {ItemID.OriginSigil,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 51, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.BirthSigil,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 52, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.LifeSigil,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 53, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.DeathSigil,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 54, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},

            {ItemID.ClaydollSuit,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 56, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.KimonoCowgirl,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 57, data = 1 }}},
            {ItemID.Valkyria,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 58, data = 1 }}},
            {ItemID.LittleDevil,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 59, data = 1 }}},
            {ItemID.EasternEurope,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 60, data = 1 }}},

            {ItemID.Whip,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 1 }}},
            {ItemID.ChainWhip,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 2 }}},
            {ItemID.FlailWhip,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 3 }}},

            {ItemID.Knife,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 63, data = 1 }}},
            {ItemID.Rapier,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 64, data = 1 }}},
            {ItemID.Axe,                        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 65, data = 1 }}},
            {ItemID.Katana,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 66, data = 1 }}},
            {ItemID.Shuriken,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 67, data = 1 }}},
            {ItemID.RollingShuriken,            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 68, data = 1 }}},
            {ItemID.EarthSpear,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 69, data = 1 }}},
            {ItemID.Flare,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 70, data = 1 }}},
            {ItemID.Bomb,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 71, data = 1 }}},
            {ItemID.Chakram,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 72, data = 1 }}},
            {ItemID.Caltrops,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 73, data = 1 }}},
            {ItemID.Pistol,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 74, data = 1 }}},

            {ItemID.Buckler,                    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 1 }}},
            {ItemID.SilverShield,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 2 }}},
            {ItemID.AngelShield,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 3 }}},

            {ItemID.AnkhJewel,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 76, data = 1 }}},

            {ItemID.Xelputter,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 77, data = 1 }}},
            {ItemID.YagooMapReader,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 78, data = 1 }}},
            {ItemID.YagooMapStreet,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 79, data = 1 }}},
            {ItemID.TextTrax,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 80, data = 1 }}},
            {ItemID.RuinsEncylopedia,           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 81, data = 1 }}},
            {ItemID.Mantra,                     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 82, data = 1 }}},
            {ItemID.Guild,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 83, data = 1 }}},
            {ItemID.Research,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 84, data = 1 }}},
            {ItemID.EngaMusica,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 85, data = 1 }}},
            {ItemID.BeoEglana,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 86, data = 1 }}},
            {ItemID.Alert,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 87, data = 1 }}},
            {ItemID.Snapshot,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 88, data = 1 }}},
            {ItemID.SkullReader,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 89, data = 1 }}},
            {ItemID.RaceScanner,                new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 90, data = 1 }}},
            {ItemID.DeathVillage,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 91, data = 1 }}},
            {ItemID.RoseandCamelia,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 92, data = 1 }}},
            {ItemID.SpaceCapstarII,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 93, data = 1 }}},
            {ItemID.LonelyHouseMoving,          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 94, data = 1 }}},
            {ItemID.MekuriMaster,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 95, data = 1 }}},
            {ItemID.BounceShot,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 96, data = 1 }}},
            {ItemID.MiracleWitch,               new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 97, data = 1 }}},
            {ItemID.FutureDevelopmentCompany,   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 98, data = 1 }}},
            {ItemID.LaMulana,                   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 99, data = 1 }}},
            {ItemID.LaMulana2,                  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 100, data = 1 }}},

            {ItemID.SacredOrb0,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 101, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb1,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 102, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb2,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 103, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb3,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 104, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb4,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 105, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb5,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 106, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb6,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 107, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb7,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 108, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb8,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 109, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},
            {ItemID.SacredOrb9,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 110, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 2,   data = 1 }}},

            {ItemID.Map1,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 111, data = 1 }}},
            {ItemID.Map2,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 112, data = 1 }}},
            {ItemID.Map3,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 113, data = 1 }}},
            {ItemID.Map4,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 114, data = 1 }}},
            {ItemID.Map5,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 115, data = 1 }}},
            {ItemID.Map6,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 116, data = 1 }}},
            {ItemID.Map7,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 117, data = 1 }}},
            {ItemID.Map8,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 118, data = 1 }}},
            {ItemID.Map9,                       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 119, data = 1 }}},
            {ItemID.Map10,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 120, data = 1 }}},
            {ItemID.Map11,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 121, data = 1 }}},
            {ItemID.Map12,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 122, data = 1 }}},
            {ItemID.Map13,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 123, data = 1 }}},
            {ItemID.Map14,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 124, data = 1 }}},
            {ItemID.Map15,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 125, data = 1 }}},
            {ItemID.Map16,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 126, data = 1 }}},
            {ItemID.Map17,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 127, data = 1 }}},
            {ItemID.Map18,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 128, data = 1 }}},
            {ItemID.Map19,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 129, data = 1 }}},
            {ItemID.Map20,                      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 130, data = 1 }}},

            {ItemID.AnkhJewel1,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 131, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel2,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 132, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel3,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 133, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel4,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 134, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel5,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 135, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel6,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 136, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel7,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 137, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel8,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 138, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.AnkhJewel9,                 new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 139, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},

            {ItemID.CrystalSkull1,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 140, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull2,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 141, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull3,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 142, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull4,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 143, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull5,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 144, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull6,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 145, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull7,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 146, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull8,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 147, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull9,              new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 148, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull10,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 149, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull11,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 150, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {ItemID.CrystalSkull12,             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 151, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}}
        };
        
        //mostly used for shop and npc items
        private static readonly Dictionary<ItemID, ItemInfo> itemData = new Dictionary<ItemID, ItemInfo>
        {
            {ItemID.HandScanner,                  new ItemInfo("H Scanner",        "H Scanner",         "item",     10, 1)},
            {ItemID.DjedPillar,                   new ItemInfo("Djed Pillar",      "Djed Pillar",       "item",     50, 1)},
            {ItemID.Mjolnir,                      new ItemInfo("Mjolnir",          "Mjolnir",           "item",     50, 1)},
            {ItemID.Beherit,                      new ItemInfo("Beherit",          "Beherit",           "item",     50, 1)},
            {ItemID.AncientBattery,               new ItemInfo("Battery",          "Battery",           "item",     50, 1)},
            {ItemID.LampofTime,                   new ItemInfo("Lamp",             "Lamp",              "item",     50, 1)},
            {ItemID.PochetteKey,                  new ItemInfo("P Key",            "P Key",             "item",     50, 1)},
            {ItemID.PyramidCrystal,               new ItemInfo("Crystal P",        "Crystal P",         "item",     50, 1)},
            {ItemID.CrystalSkull,                 new ItemInfo("Crystal S",        "Crystal S",         "item",     50, 1)},
            {ItemID.Vessel,                       new ItemInfo("Vessel",           "Vessel",            "item",     50, 1)},
            {ItemID.Pepper,                       new ItemInfo("Pepper",           "Pepper",            "item",     50, 1)},
            {ItemID.EggofCreation,                new ItemInfo("Egg",              "Egg",               "item",     50, 1)},
            {ItemID.GiantsFlute,                  new ItemInfo("G Pipe",           "G Pipe",            "item",     120, 1)},
            {ItemID.CogofAntiquity,               new ItemInfo("Gear",             "Gear",              "item",     50, 1)},
            {ItemID.MulanaTalisman,               new ItemInfo("M Talisman",       "M Talisman",        "item",     80, 1)},
                                                                                                                    
            {ItemID.MobileSuperx3P,               new ItemInfo("MSX3p",            "MSX",               "item",     150, 2)},
            {ItemID.ShellHorn,                    new ItemInfo("Shell Horn",       "Shell Horn",        "item",     50, 1)},
            {ItemID.HolyGrail,                    new ItemInfo("Holy Grail",       "Holy Grail",        "item",     50, 1)},
            {ItemID.FairyPass,                    new ItemInfo("F Pass",           "F Pass",            "item",     50, 1)},
            {ItemID.Gloves,                       new ItemInfo("Glove",            "Glove",             "item",     50, 1)},
            {ItemID.DinosaurFigure,               new ItemInfo("D Figure",         "D Figure",          "item",     50, 1)},
            {ItemID.GaleFibula,                   new ItemInfo("G Band",           "G Band",            "item",     50, 1)},
            {ItemID.FlameTorc,                    new ItemInfo("F Torque",         "F Torque",          "item",     50, 1)},
            {ItemID.Vajra,                        new ItemInfo("Vajra",            "Vajra",             "item",     100, 1)},
            {ItemID.PowerBand,                    new ItemInfo("Power Band",       "Power Band",        "item",     50, 1)},
            {ItemID.BronzeMirror,                 new ItemInfo("B Mirror",         "B Mirror",          "item",     80, 1)},
            {ItemID.Perfume,                      new ItemInfo("Perfume",          "Perfume",           "item",     100, 1)},
            {ItemID.IceCloak,                     new ItemInfo("Ice Cape",         "Ice Cape",          "item",     50, 1)},
            {ItemID.NemeanFur,                    new ItemInfo("Fur",              "Fur",               "item",     120, 1)},
            {ItemID.Gauntlet,                     new ItemInfo("Gauntlet",         "Gauntlet",          "item",     110, 1)},
            {ItemID.Anchor,                       new ItemInfo("Anchor",           "Anchor",            "item",     50, 1)},
            {ItemID.FreyasPendant,                new ItemInfo("F Pendant",        "F Pendant",         "item",     50, 1)},
            {ItemID.TotemPole,                    new ItemInfo("T Pole",           "T Pole",            "item",     100, 1)},
            {ItemID.GrappleClaw,                  new ItemInfo("G Claw",           "G Claw",            "item",     50, 1)},
            {ItemID.Spaulder,                     new ItemInfo("Spaulder",         "Spaulder",          "item",     120, 1)},
            {ItemID.Scalesphere,                  new ItemInfo("Scalesphere",      "Scalesphere",       "item",     50, 1)},
            {ItemID.Crucifix,                     new ItemInfo("Crucifix",         "Crucifix",          "item",     100, 1)},
            {ItemID.GaneshaTalisman,              new ItemInfo("Gold Bangle",      "Gold Bangle",       "item",     50, 1)},
            {ItemID.MaatsFeather,                 new ItemInfo("M Feather",        "M Feather",         "item",     80, 1)},
            {ItemID.Ring,                         new ItemInfo("Ring",             "Ring",              "item",     100, 1)},
            {ItemID.Bracelet,                     new ItemInfo("Bracelet",         "Bracelet",          "item",     100, 1)},
            {ItemID.Feather,                      new ItemInfo("Feather",          "Feather",           "item",     50, 1)},
            {ItemID.Scriptures,                   new ItemInfo("Scriptures",       "Scriptures",        "item",     100, 1)},
            {ItemID.FreysShip,                    new ItemInfo("F Ship",           "F Ship",            "item",     50, 1)},
            {ItemID.Codices,                      new ItemInfo("Pandora Box",      "Pandora Box",       "item",     80, 1)},
            {ItemID.SnowShoes,                    new ItemInfo("Snow Shoes",       "Snow Shoes",        "item",     50, 1)},
            {ItemID.Harp,                         new ItemInfo("Harp",             "Harp",              "item",     150, 1)},
            {ItemID.BookoftheDead,                new ItemInfo("Book",             "Book",              "item",     100, 1)},
            {ItemID.LightScythe,                  new ItemInfo("L Scythe",         "L Scythe",          "item",     50, 1)},
            {ItemID.DestinyTablet,                new ItemInfo("Destiny Tablet",   "Destiny Tablet",    "item",     150, 1)},
            {ItemID.SecretTreasureofLife,         new ItemInfo("Secret Treasure",  "Secret Treasure",   "item",     150, 1)},
            
            {ItemID.OriginSigil,                  new ItemInfo("Origin Seal",      "Origin Seal",       "item",     40,  1)},
            {ItemID.BirthSigil,                   new ItemInfo("Birth Seal",       "Birth Seal",        "item",     60,  1)},
            {ItemID.LifeSigil,                    new ItemInfo("Life Seal",        "Life Seal",         "item",     80, 1)},
            {ItemID.DeathSigil,                   new ItemInfo("Death Seal",       "Death Seal",        "item",     120, 1)},
            
            {ItemID.ClaydollSuit,                 new ItemInfo("Clay Doll",        "Clay Doll",         "fashion",  100, 1)},
            {ItemID.KimonoCowgirl,                new ItemInfo("Kimono Cowgirl",   "Kimono Cowgirl",    "fashion",  0,   1)},
            {ItemID.Valkyria,                     new ItemInfo("Valkyria",         "Valkyria",          "fashion",  0,   1)},
            {ItemID.LittleDevil,                  new ItemInfo("Little Devil",     "Little Devil",      "fashion",  0,   1)},
            {ItemID.EasternEurope,                new ItemInfo("Eastern Europe",   "Eastern Europe",    "fashion",  0,   1)},
            
            {ItemID.Whip,                         new ItemInfo("Whip",             "Whip",              "weapon",   0,   1)},
            {ItemID.ChainWhip,                    new ItemInfo("Whip2",            "Whip2",             "weapon",   80,  1)},
            {ItemID.FlailWhip,                    new ItemInfo("Whip3",            "Whip3",             "weapon",   160, 1)},
            
            {ItemID.Knife,                        new ItemInfo("Knife",            "Knife",             "weapon",   40,  1)},
            {ItemID.Rapier,                       new ItemInfo("Rapier",           "Rapier",            "weapon",   80,  1)},
            {ItemID.Axe,                          new ItemInfo("Axe",              "Axe",               "weapon",   100, 1)},
            {ItemID.Katana,                       new ItemInfo("Katana",           "Katana",            "weapon",   100, 1)},
            {ItemID.Shuriken,                     new ItemInfo("Shuriken",         "Shuriken",          "weapon",   30,  1)},
            {ItemID.RollingShuriken,              new ItemInfo("R-Shuriken",       "R-Shuriken",        "weapon",   30,  1)},
            {ItemID.EarthSpear,                   new ItemInfo("E-Spear",          "E-Spear",           "weapon",   30,  1)},
            {ItemID.Flare,                        new ItemInfo("Flare Gun",        "Flare Gun",         "weapon",   30,  1)},
            {ItemID.Bomb,                         new ItemInfo("Bomb",             "Bomb",              "weapon",   30,  1)},
            {ItemID.Chakram,                      new ItemInfo("Chakram",          "Chakram",           "weapon",   30,  1)},
            {ItemID.Caltrops,                     new ItemInfo("Caltrops",         "Caltrops",          "weapon",   30,  1)},
            {ItemID.Pistol,                       new ItemInfo("Pistol",           "Pistol",            "weapon",   200, 1)},
            
            {ItemID.Buckler,                      new ItemInfo("Shield",           "Shield",            "weapon",   10,  1)},
            {ItemID.SilverShield,                 new ItemInfo("Shield2",          "Shield2",           "weapon",   80,  1)},
            {ItemID.AngelShield,                  new ItemInfo("Shield3",          "Shield3",           "weapon",   200, 1)},
            
            {ItemID.AnkhJewel,                    new ItemInfo("Ankh Jewel",       "Ankh Jewel",        "weapon",   50,  1)},
            
            {ItemID.Xelputter,                    new ItemInfo("Xelputter",        "Xelputter",         "soft",     120,  1)},
            {ItemID.YagooMapReader,               new ItemInfo("G Map",            "G Map",             "soft",     120,  1)},
            {ItemID.YagooMapStreet,               new ItemInfo("G Street",         "G Street",          "soft",     120,  1)},
            {ItemID.TextTrax,                     new ItemInfo("TextTrax",         "TextTrax",          "soft",     120,  1)},
            {ItemID.RuinsEncylopedia,             new ItemInfo("R Book",           "R Book",            "soft",     120,  1)},
            {ItemID.Mantra,                       new ItemInfo("Mantra",           "Mantra",            "soft",     50,  1)},
            {ItemID.Guild,                        new ItemInfo("Guild",            "Guild",             "soft",     120,  1)},
            {ItemID.Research,                     new ItemInfo("Research",         "Research",          "soft",     120,  1)},
            {ItemID.EngaMusica,                   new ItemInfo("Enga Musica",      "Enga Musica",       "soft",     50,  1)},
            {ItemID.BeoEglana,                    new ItemInfo("Beo Eg-lana",      "Beo Eg-lana",       "soft",     120,  1)},
            {ItemID.Alert,                        new ItemInfo("Alarm",            "Alarm",             "soft",     120,  1)},
            {ItemID.Snapshot,                     new ItemInfo("Snapshots",        "Snapshots",         "soft",     50,  1)},
            {ItemID.SkullReader,                  new ItemInfo("Skull",            "Skull",             "soft",     120,  1)},
            {ItemID.RaceScanner,                  new ItemInfo("Race Reader",      "Race Reader",       "soft",     120,  1)},
            {ItemID.DeathVillage,                 new ItemInfo("Death Village",    "Death Village",     "soft",     120,  1)},
            {ItemID.RoseandCamelia,               new ItemInfo("R and C",          "R and C",           "soft",     120,  1)},
            {ItemID.SpaceCapstarII,               new ItemInfo("Capstar II",       "Capstar II",        "soft",     120,  1)},
            {ItemID.LonelyHouseMoving,            new ItemInfo("L House Moving",   "L House Moving",    "soft",     50,  1)},
            {ItemID.MekuriMaster,                 new ItemInfo("Mekuri Master",    "Mekuri Master",     "soft",     120,  1)},
            {ItemID.BounceShot,                   new ItemInfo("Bounce Shot",      "Bounce Shot",       "soft",     120,  1)},
            {ItemID.MiracleWitch,                 new ItemInfo("Miracle Witch",    "Miracle Witch",     "soft",     120,  1)},
            {ItemID.FutureDevelopmentCompany,     new ItemInfo("Future DC",        "Future DC",         "soft",     120,  1)},
            {ItemID.LaMulana,                     new ItemInfo("La-Mulana",        "La-Mulana",         "soft",     120,  1)},
            {ItemID.LaMulana2,                    new ItemInfo("La-Mulana2",       "La-Mulana2",        "soft",     120,  1)},

            {ItemID.SacredOrb0,                   new ItemInfo("Sacred Orb",       "Sacred Orb0",       "item",     40,  1)},
            {ItemID.SacredOrb1,                   new ItemInfo("Sacred Orb",       "Sacred Orb1",       "item",     40,  1)},
            {ItemID.SacredOrb2,                   new ItemInfo("Sacred Orb",       "Sacred Orb2",       "item",     40,  1)},
            {ItemID.SacredOrb3,                   new ItemInfo("Sacred Orb",       "Sacred Orb3",       "item",     50,  1)},
            {ItemID.SacredOrb4,                   new ItemInfo("Sacred Orb",       "Sacred Orb4",       "item",     50,  1)},
            {ItemID.SacredOrb5,                   new ItemInfo("Sacred Orb",       "Sacred Orb5",       "item",     50, 1)},
            {ItemID.SacredOrb6,                   new ItemInfo("Sacred Orb",       "Sacred Orb6",       "item",     60, 1)},
            {ItemID.SacredOrb7,                   new ItemInfo("Sacred Orb",       "Sacred Orb7",       "item",     60, 1)},
            {ItemID.SacredOrb8,                   new ItemInfo("Sacred Orb",       "Sacred Orb8",       "item",     60, 1)},
            {ItemID.SacredOrb9,                   new ItemInfo("Sacred Orb",       "Sacred Orb9",       "item",     60, 1)},

            {ItemID.Map1,                         new ItemInfo("Map",              "Map1",              "item",     40,  1)},
            {ItemID.Map2,                         new ItemInfo("Map",              "Map2",              "item",     40,  1)},
            {ItemID.Map3,                         new ItemInfo("Map",              "Map3",              "item",     40,  1)},
            {ItemID.Map4,                         new ItemInfo("Map",              "Map4",              "item",     40,  1)},
            {ItemID.Map5,                         new ItemInfo("Map",              "Map5",              "item",     50,  1)},
            {ItemID.Map6,                         new ItemInfo("Map",              "Map6",              "item",     50,  1)},
            {ItemID.Map7,                         new ItemInfo("Map",              "Map7",              "item",     50,  1)},
            {ItemID.Map8,                         new ItemInfo("Map",              "Map8",              "item",     50,  1)},
            {ItemID.Map9,                         new ItemInfo("Map",              "Map9",              "item",     60,  1)},
            {ItemID.Map10,                        new ItemInfo("Map",              "Map10",             "item",     60,  1)},
            {ItemID.Map11,                        new ItemInfo("Map",              "Map11",             "item",     60,  1)},
            {ItemID.Map12,                        new ItemInfo("Map",              "Map12",             "item",     60,  1)},
            {ItemID.Map13,                        new ItemInfo("Map",              "Map13",             "item",     70,  1)},
            {ItemID.Map14,                        new ItemInfo("Map",              "Map14",             "item",     70,  1)},
            {ItemID.Map15,                        new ItemInfo("Map",              "Map15",             "item",     70,  1)},
            {ItemID.Map16,                        new ItemInfo("Map",              "Map16",             "item",     70,  1)},
            {ItemID.Map17,                        new ItemInfo("Map",              "Map17",             "item",     80,  1)},
            {ItemID.Map18,                        new ItemInfo("Map",              "Map18",             "item",     80,  1)},
            {ItemID.Map19,                        new ItemInfo("Map",              "Map19",             "item",     80,  1)},
            {ItemID.Map20,                        new ItemInfo("Map",              "Map20",             "item",     80,  1)},
            
            {ItemID.AnkhJewel1,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel1",       "weapon",   40,  1)},
            {ItemID.AnkhJewel2,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel2",       "weapon",   40,  1)},
            {ItemID.AnkhJewel3,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel3",       "weapon",   40,  1)},
            {ItemID.AnkhJewel4,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel4",       "weapon",   50,  1)},
            {ItemID.AnkhJewel5,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel5",       "weapon",   50,  1)},
            {ItemID.AnkhJewel6,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel6",       "weapon",   50,  1)},
            {ItemID.AnkhJewel7,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel7",       "weapon",   60,  1)},
            {ItemID.AnkhJewel8,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel8",       "weapon",   60,  1)},
            {ItemID.AnkhJewel9,                   new ItemInfo("Ankh Jewel",       "Ankh Jewel9",       "weapon",   60,  1)},
            
            {ItemID.CrystalSkull1,                new ItemInfo("Crystal S",        "Crystal S1",        "item",     100,  1)},
            {ItemID.CrystalSkull2,                new ItemInfo("Crystal S",        "Crystal S2",        "item",     100,  1)},
            {ItemID.CrystalSkull3,                new ItemInfo("Crystal S",        "Crystal S3",        "item",     100,  1)},
            {ItemID.CrystalSkull4,                new ItemInfo("Crystal S",        "Crystal S4",        "item",     100,  1)},
            {ItemID.CrystalSkull5,                new ItemInfo("Crystal S",        "Crystal S5",        "item",     100,  1)},
            {ItemID.CrystalSkull6,                new ItemInfo("Crystal S",        "Crystal S6",        "item",     100,  1)},
            {ItemID.CrystalSkull7,                new ItemInfo("Crystal S",        "Crystal S7",        "item",     100,  1)},
            {ItemID.CrystalSkull8,                new ItemInfo("Crystal S",        "Crystal S8",        "item",     100,  1)},
            {ItemID.CrystalSkull9,                new ItemInfo("Crystal S",        "Crystal S9",        "item",     100,  1)},
            {ItemID.CrystalSkull10,               new ItemInfo("Crystal S",        "Crystal S10",       "item",     100,  1)},
            {ItemID.CrystalSkull11,               new ItemInfo("Crystal S",        "Crystal S11",       "item",     100,  1)},
            {ItemID.CrystalSkull12,               new ItemInfo("Crystal S",        "Crystal S12",       "item",     100,  1)},

            {ItemID.Weights,                      new ItemInfo("Weight",           "Weight",            "item",     10,  5)},
            {ItemID.ShurikenAmmo,                 new ItemInfo("Shuriken-b",       "Shuriken-b",        "weapon",   10,  10)},
            {ItemID.RollingShurikenAmmo,          new ItemInfo("R-Shuriken-b",     "R-Shuriken-b",      "weapon",   10,  10)},
            {ItemID.EarthSpearAmmo,               new ItemInfo("E-Spear-b",        "E-Spear-b",         "weapon",   10,  10)},
            {ItemID.FlareAmmo,                    new ItemInfo("Flare Gun-b",      "Flare Gun-b",       "weapon",   15,  10)},
            {ItemID.BombAmmo,                     new ItemInfo("Bomb-b",           "Bomb-b",            "weapon",   30,  5)},
            {ItemID.ChakramAmmo,                  new ItemInfo("Chakram-b",        "Chakram-b",         "weapon",   20,  1)},
            {ItemID.CaltropsAmmo,                 new ItemInfo("Caltrops-b",       "Caltrops-b",        "weapon",   20,  10)},
            {ItemID.PistolAmmo,                   new ItemInfo("Pistol-b",         "Pistol-b",          "weapon",   400, 1)}
        };

    }

    public class ItemInfo
    {
        public string boxName;
        public string shopName;
        public string shopType;
        public int shopPrice;
        public int shopAmount;

        public ItemInfo(string boxName, string shopName, string type, int price, int amount)
        {
            this.boxName = boxName;
            this.shopName = shopName;
            this.shopType = type;
            this.shopPrice = price;
            this.shopAmount = amount;
        }
    }

    //NOTE:maybe just use the existing itemdatabase enum, but if add stuff like mantras to randomisation that wont be viable
    public enum ItemID
    {
        Default = 0,
        HandScanner,
        DjedPillar,
        Mjolnir,
        Beherit,
        AncientBattery,
        LampofTime,
        PochetteKey,
        PyramidCrystal,
        CrystalSkull,
        Vessel,
        Pepper,
        EggofCreation,
        GiantsFlute,
        CogofAntiquity,
        MulanaTalisman,
        MobileSuperx3P,
        ShellHorn,
        HolyGrail,
        FairyPass,
        Gloves,
        DinosaurFigure,
        GaleFibula,
        FlameTorc,
        Vajra,
        PowerBand,
        BronzeMirror,
        Perfume,
        IceCloak,
        NemeanFur,
        Gauntlet,
        Anchor,
        FreyasPendant,
        TotemPole,
        GrappleClaw,
        Spaulder,
        Scalesphere,
        Crucifix,
        GaneshaTalisman,
        MaatsFeather,
        Ring,
        Bracelet,
        Feather,
        Scriptures,
        FreysShip,
        Codices,
        SnowShoes,
        Harp,
        BookoftheDead,
        LightScythe,
        DestinyTablet,
        SecretTreasureofLife,
        OriginSigil,
        BirthSigil,
        LifeSigil,
        DeathSigil,
        ClaydollSuit,
        KimonoCowgirl,
        Valkyria,
        LittleDevil,
        EasternEurope,
        Whip,
        ChainWhip,
        FlailWhip,
        Knife,
        Rapier,
        Axe,
        Katana,
        Shuriken,
        RollingShuriken,
        EarthSpear,
        Flare,
        Bomb,
        Chakram,
        Caltrops,
        Pistol,
        Buckler,
        SilverShield,
        AngelShield,
        AnkhJewel,
        Xelputter,
        YagooMapReader,
        YagooMapStreet,
        TextTrax,
        RuinsEncylopedia,
        Mantra,
        Guild,
        Research,
        EngaMusica,
        BeoEglana,
        Alert,
        Snapshot,
        SkullReader,
        RaceScanner,
        DeathVillage,
        RoseandCamelia,
        SpaceCapstarII,
        LonelyHouseMoving,
        MekuriMaster,
        BounceShot,
        MiracleWitch,
        FutureDevelopmentCompany,
        LaMulana,
        LaMulana2,
        SacredOrb0,
        SacredOrb1,
        SacredOrb2,
        SacredOrb3,
        SacredOrb4,
        SacredOrb5,
        SacredOrb6,
        SacredOrb7,
        SacredOrb8,
        SacredOrb9,
        Map1,
        Map2,
        Map3,
        Map4,
        Map5,
        Map6,
        Map7,
        Map8,
        Map9,
        Map10,
        Map11,
        Map12,
        Map13,
        Map14,
        Map15,
        Map16,
        Map17,
        Map18,
        Map19,
        Map20,
        AnkhJewel1,
        AnkhJewel2,
        AnkhJewel3,
        AnkhJewel4,
        AnkhJewel5,
        AnkhJewel6,
        AnkhJewel7,
        AnkhJewel8,
        AnkhJewel9,
        CrystalSkull1,
        CrystalSkull2,
        CrystalSkull3,
        CrystalSkull4,
        CrystalSkull5,
        CrystalSkull6,
        CrystalSkull7,
        CrystalSkull8,
        CrystalSkull9,
        CrystalSkull10,
        CrystalSkull11,
        CrystalSkull12,
        Weights,
        ShurikenAmmo,
        RollingShurikenAmmo,
        EarthSpearAmmo,
        FlareAmmo,
        BombAmmo,
        ChakramAmmo,
        CaltropsAmmo,
        PistolAmmo,
    }
}
