using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using L2Flag;

namespace LM2TestMod
{
    public abstract class ItemFlags
    {
        private static readonly Dictionary<string, L2FlagBoxEnd[]> getFlags = new Dictionary<string, L2FlagBoxEnd[]>
        {
            {"H Scanner",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 0, data = 1 }}},
            {"Djed Pillar",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 1, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Mjolnir",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 2, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Beherit",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 3, data = 1 }}},
            {"Battery",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 4, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Lamp",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 5, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"P Key",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 6, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal P",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 7, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 8, data = 1 }}},
            {"Vessel",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 9, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Pepper",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 10, data = 1 }}},
            {"Egg",             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 11, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"G Pipe",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 12, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Gear",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 13, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"M Talisman",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 14, data = 1 }}},

            {"MSX",             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 15, data = 2 }}},
            {"Shell Horn",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 16, data = 1 }}},
            {"Holy Grail",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 17, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"F Pass",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 18, data = 1 }}},
            {"Glove",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 19, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"D Figure",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 20, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"G Band",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 21, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"F Torque",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 22, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Vajra",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 23, data = 1 }}},
            {"Power Band",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 24, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"B Mirror",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 25, data = 1 }}},
            {"Perfume",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 26, data = 1 }}},
            {"Ice Cape",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 27, data = 1 }}},
            {"Fur",             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 28, data = 1 }}},
            {"Gauntlet",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 29, data = 1 }}},
            {"Anchor",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 30, data = 1 }}},
            {"F Pendant",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 31, data = 1 }}},
            {"T Pole",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 32, data = 1 }}},
            {"G Claw",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 33, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Spaulder",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 34, data = 1 }}},
            {"Scalesphere",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 35, data = 1 }}},
            {"Crucifix",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 36, data = 1 }}},
            {"Gold Bangle",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 37, data = 1 },   //Ganesha's Talisman
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"M Feather",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 38, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ring",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 39, data = 1 }}},
            {"Bracelet",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 40, data = 1 }}},
            {"Feather",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 41, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Scriptures",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 42, data = 1 }}},
            {"F Ship",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 43, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Pandora Box",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 44, data = 1 }}},
            {"Snow Shoes",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 45, data = 1 }}},
            {"Harp",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 46, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Book",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 47, data = 1 }}},
            {"L Scythe",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 48, data = 1 }}},
            {"Destiny Tablet",  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 49, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Secret Treasure", new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 50, data = 1 }}},

            {"Origin Seal",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 51, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Birth Seal",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 52, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Life Seal",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 53, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Death Seal",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 54, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},

            {"Clay Doll",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 56, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Kimono Cowgirl",  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 57, data = 1 }}},
            {"Valkyria",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 58, data = 1 }}},
            {"Little Devil",    new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 59, data = 1 }}},
            {"Eastern Europe",  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 60, data = 1 }}},

            {"Whip",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 1 }}},
            {"Whip2",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 2 }}},
            {"Whip3",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 62, data = 3 }}},

            {"Knife",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 63, data = 1 }}},
            {"Rapier",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 64, data = 1 }}},
            {"Axe",             new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 65, data = 1 }}},
            {"Katana",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 66, data = 1 }}},
            {"Shuriken",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 67, data = 1 }}},
            {"R-Shuriken",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 68, data = 1 }}},
            {"E-Spear",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 69, data = 1 }}},
            {"Flare Gun",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 70, data = 1 }}},
            {"Bomb",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 71, data = 1 }}},
            {"Chakram",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 72, data = 1 }}},
            {"Caltrops",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 73, data = 1 }}},
            {"Pistol",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 74, data = 1 }}},

            {"Shield",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 1 }}},
            {"Shield2",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 2 }}},
            {"Shield3",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 75, data = 3 }}},

            {"Ankh Jewel",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 76, data = 1 }}},

            {"Xelputter",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 77, data = 1 }}},
            {"G Map",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 78, data = 1 }}},
            {"G Street",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 79, data = 1 }}},
            {"TextTrax",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 80, data = 1 }}},
            {"R Book",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 81, data = 1 }}},
            {"Mantra",          new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 82, data = 1 }}},
            {"Guild",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 83, data = 1 }}},
            {"Research",        new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 84, data = 1 }}},
            {"Enga Musica",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 85, data = 1 }}},
            {"Beo Eg-lana",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 86, data = 1 }}},
            {"Alarm",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 87, data = 1 }}},
            {"Snapshots",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 88, data = 1 }}},
            {"Skull",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 89, data = 1 }}},
            {"Race Reader",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 90, data = 1 }}},
            {"Death Village",   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 91, data = 1 }}},
            {"R and C",         new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 92, data = 1 }}},
            {"Capstar II",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 93, data = 1 }}},
            {"L House Moving",  new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 94, data = 1 }}},
            {"Mekuri Master",   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 95, data = 1 }}},
            {"Bounce Shot",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 96, data = 1 }}},
            {"Miracle Witch",   new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 97, data = 1 }}},
            {"Future DC",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 98, data = 1 }}},
            {"La-Mulana",       new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 99, data = 1 }}},
            {"La-Mulana2",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 100, data = 1 }}},

            {"Sacred Orb0",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 101, data = 1 }}},
            {"Sacred Orb1",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 102, data = 1 }}},
            {"Sacred Orb3",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 104, data = 1 }}},
            {"Sacred Orb4",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 105, data = 1 }}},
            {"Sacred Orb5",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 106, data = 1 }}},
            {"Sacred Orb6",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 107, data = 1 }}},
            {"Sacred Orb7",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 108, data = 1 }}},
            {"Sacred Orb8",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 109, data = 1 }}},
            {"Sacred Orb9",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 110, data = 1 }}},

            {"Map1",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 111, data = 1 }}},
            {"Map2",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 112, data = 1 }}},
            {"Map3",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 113, data = 1 }}},
            {"Map4",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 114, data = 1 }}},
            {"Map5",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 115, data = 1 }}},
            {"Map6",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 116, data = 1 }}},
            {"Map7",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 117, data = 1 }}},
            {"Map8",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 118, data = 1 }}},
            {"Map9",            new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 119, data = 1 }}},
            {"Map10",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 120, data = 1 }}},
            {"Map11",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 121, data = 1 }}},
            {"Map12",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 122, data = 1 }}},
            {"Map13",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 123, data = 1 }}},
            {"Map14",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 124, data = 1 }}},
            {"Map15",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 125, data = 1 }}},
            {"Map16",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 126, data = 1 }}},
            {"Map17",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 127, data = 1 }}},
            {"Map18",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 128, data = 1 }}},
            {"Map19",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 129, data = 1 }}},
            {"Map20",           new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 130, data = 1 }}},

            {"Ankh Jewel1",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 131, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel2",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 132, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel3",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 133, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel4",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 134, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel5",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 135, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel6",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 136, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel7",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 137, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel8",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 138, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Ankh Jewel9",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 139, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},

            {"Crystal S1",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 140, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S2",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 141, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S3",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 142, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S4",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 143, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S5",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 144, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S6",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 145, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S7",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 146, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S8",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 147, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S9",      new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 148, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S10",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 149, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S11",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 150, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}},
            {"Crystal S12",     new L2FlagBoxEnd[]{ new L2FlagBoxEnd { calcu = CALCU.EQR, seet_no1 = 2, flag_no1 = 151, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 0, flag_no1 = 32, data = 1 },
                                                    new L2FlagBoxEnd { calcu = CALCU.ADD, seet_no1 = 3, flag_no1 = 30, data = 4 }}}
        };

        private static readonly Dictionary<string, L2FlagBoxParent[]> openFlags = new Dictionary<string, L2FlagBoxParent[]>
        {
            {"H Scanner",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 0,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Djed Pillar",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 1,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Mjolnir",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 2,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Beherit",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 3,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Battery",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 4,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Lamp",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 5,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"P Key",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 6,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal P",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 7,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 8,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Vessel",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 9,   comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Pepper",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 10,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Egg",             new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 11,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"G Pipe",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 12,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Gear",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 13,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"M Talisman",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 14,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"MSX",             new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 15,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Shell Horn",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 16,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Holy Grail",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 17,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"F Pass",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 18,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Glove",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 19,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"D Figure",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 20,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"G Band",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 21,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"F Torque",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 22,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Vajra",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 23,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Power Band",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 24,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"B Mirror",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 25,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Perfume",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 26,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ice Cape",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 27,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Fur",             new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 28,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Gauntlet",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 29,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Anchor",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 30,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"F Pendant",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 31,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"T Pole",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 32,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"G Claw",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 33,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Spaulder",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 34,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Scalesphere",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 35,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crucifix",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 36,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Gold Bangle",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 37,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"M Feather",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 38,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ring",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 39,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Bracelet",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 40,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Feather",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 41,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Scriptures",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 42,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"F Ship",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 43,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Pandora Box",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 44,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Snow Shoes",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 45,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Harp",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 46,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Book",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 47,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"L Scythe",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 48,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Destiny Tablet",  new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 49,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Secret Treasure", new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 50,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Origin Seal",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 51,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Birth Seal",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 52,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Life Seal",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 53,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Death Seal",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 54,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Clay Doll",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 56,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Kimono Cowgirl",  new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 57,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Valkyria",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 58,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Little Devil",    new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 59,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Eastern Europe",  new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 60,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Whip",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 62,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Whip2",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 62,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Whip3",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 62,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Knife",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 63,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Rapier",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 64,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Axe",             new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 65,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Katana",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 66,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Shuriken",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 67,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"R-Shuriken",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 68,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"E-Spear",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 69,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Flare Gun",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 70,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Bomb",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 71,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Chakram",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 72,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Caltrops",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 73,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Pistol",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 74,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Shield",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 75,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Shield2",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 75,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Shield3",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 75,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Ankh Jewel",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 76,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Xelputter",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 77,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"G Map",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 78,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"G Street",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 79,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"TextTrax",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 80,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"R Book",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 81,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Mantra",          new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 82,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Guild",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 83,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Research",        new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 84,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Enga Musica",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 85,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Beo Eg-lana",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 86,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Alarm",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 87,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Snapshots",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 88,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Skull",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 89,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Race Reader",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 90,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Death Village",   new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 91,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"R and C",         new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 92,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Capstar II",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 93,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"L House Moving",  new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 94,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Mekuri Master",   new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 95,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Bounce Shot",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 96,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Miracle Witch",   new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 97,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Future DC",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 98,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"La-Mulana",       new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 99,  comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"La-Mulana2",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 100, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Sacred Orb0",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 101, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb1",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 102, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb3",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 104, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb4",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 105, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb5",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 106, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb6",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 107, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb7",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 108, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb8",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 109, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Sacred Orb9",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 110, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Map1",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 111, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map2",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 112, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map3",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 113, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map4",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 114, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map5",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 115, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map6",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 116, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map7",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 117, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map8",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 118, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map9",            new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 119, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map10",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 120, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map11",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 121, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map12",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 122, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map13",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 123, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map14",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 124, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map15",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 125, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map16",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 126, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map17",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 127, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map18",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 128, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map19",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 129, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Map20",           new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 130, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Ankh Jewel1",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 131, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel2",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 132, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel3",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 133, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel4",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 134, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel5",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 135, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel6",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 136, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel7",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 137, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel8",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 138, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Ankh Jewel9",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 139, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
                                                                                                                                                                                                                                                  
            {"Crystal S1",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 140, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S2",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 141, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S3",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 142, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S4",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 143, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S5",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 144, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S6",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 145, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S7",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 146, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S8",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 147, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S9",      new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 148, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S10",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 149, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S11",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 150, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}},
            {"Crystal S12",     new L2FlagBoxParent[]{ new L2FlagBoxParent { logoc =LOGIC.NON, BOX = new L2FlagBox[] { new L2FlagBox {seet_no1 = 2, flag_no1 = 151, comp = COMPARISON.GreaterEq, seet_no2 = -1, flag_no2 =1, logic = LOGIC.NON}}}}}
        };
    }
}
